# Install GNU core utilities (those that come with OS X are outdated)
brew 'coreutils'
# Install some other useful utilities like `sponge`
#brew 'moreutils'
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
brew 'findutils'
# Install GNU `sed`, overwriting the built-in `sed`
#brew install gnu-sed --default-names
# Install Bash 5
brew 'bash'
brew 'bash-completion'
# brew 'zsh'
# brew 'zsh-completions'

#brew 'homebrew/dupes/grep'
#brew 'homebrew/dupes/screen'
brew 'ack'
brew 'git'
brew 'hub'

# Mac App Store
# brew 'mas'

brew 'openssl'
# brew 'yarn'
brew 'jq'
# brew 'nvm'
brew 'unrar'
brew 'wget'
brew 'watch'
# brew 'homebrew/dupes/openssh'
brew 'nmap'
brew 'curl'
# brew 'heroku-toolbelt'
# TODO: need to run heroku update to ensure latest version
# tool to easily access gitignore boilerplates - https://github.com/simonwhitaker/gibo - https://github.com/github/gitignore
brew 'gibo'

brew 'rsync'
brew 'ssh-copy-id'
# brew 'mongodb'
brew 'thefuck'
brew 'tree'

brew 'youtube-dl'

tap 'Homebrew/cask-versions'

# verify cask install
#brew cask doctor

# macOS aerial screensaver
# cask 'aerial'
# cask 'alfred'
cask 'anvil'

cask 'backblaze'

# GPG Suite
# cask 'gpgtools'

cask 'balenaetcher'
cask 'caffeine'
# cask 'cheatsheet'
cask 'cyberduck'
#cask 'dash'
cask 'dbeaver-community'
# cask 'docker-toolbox'
cask 'docker'

# Hide status bar icons
# cask 'bartender'
cask 'dozer'

# Put output of any script in status bar
# cask 'bitbar'

cask 'dropbox'
# cask 'firefox'
# cask 'firefox-beta'
cask 'fluid'
cask 'google-chrome'
# cask 'google-chrome-beta'
cask 'google-chrome-canary'
cask 'grandperspective'
# cask 'growlnotify'
# cask 'hazel'
cask 'insomnia'
cask 'iterm2'
# cask 'kap'
cask 'keybase'
# cask 'keycastr'
#cask 'libreoffice'

# Firewall to block unknown outbound connections
# similar to little snitch
# relies on kernel extension which will be blocked
# in future macos release
# TODO: investigate options
#cask 'lulu'

# Mock API
cask 'mockoon'

cask 'mounty'
cask 'multifirefox'
cask 'ngrok'
#cask 'omnigraffle'

# Display dock in touch bar
cask 'pock'

cask 'rectangle'
cask 'spotify'
# install Sublime Text 3 dev - automatically links subl
cask 'sublime-text-dev'
cask 'the-unarchiver'
cask 'transmit'
cask 'virtualbox'
cask 'vlc'
# keyboards shortcuts to resize / position windows - https://www.irradiatedsoftware.com/sizeup/
# cask 'sizeup'
# Lua-based automation, including window resize / potisioning - http://www.hammerspoon.org/
# cask 'hammerspoon'

# ## PICK A MOCKUP APP
# cask 'balsamiq'
# cask 'pencil'

cask '1password'

# sshfs
# relies on kernel extension which will be blocked
# in future macos release
# cask 'osxfuse'
# TODO: not available, find alternative
#cask 'sshfs'

# new versions only available from Mac AppStore
cask 'ccmenu'

# Install useful Quick Look plugins for developers
# See https://github.com/sindresorhus/quick-look-plugins
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'
# unavailable
# cask 'betterzipql'
cask 'webpquicklook'
cask 'suspicious-package'

# build tools
cask 'homebrew/cask-versions/adoptopenjdk8'
# brew 'maven'
# brew 'gradle'

# IDEs etc.
# cask 'eclipse-java'
# cask 'sqlitebrowser'
